### ISSUE TITLE
遇到系统错误 / Encountered a system error

### ISSUE THREAD

**Issue by moscams** [SamToki/KanaMaster#1]
你好，
Hi there,

这个软件非常有趣，对我学习日语假名帮助很大，但我遇到了一些使用上的问题。
This software is very interesting and greatly helps me learn Japanese kana, but I have encountered some issues while using it.

我在完成一次游戏后遇到了系统错误，提示信息如下：
I encountered a system error after completing a game, and the error message is as follows:

> 遇到错误：“抱歉，发生了系统错误。这可能是损坏了用户数据导致的。是否前往用户数据？”

**报错截图 / Error Screenshot**

<img width="378" alt="Snipaste_2024-11-12_12-00-07" src="https://github.com/user-attachments/assets/45dc8738-03ba-4607-89e0-20ae839b2679">

**控制台截图 / Console Screenshot**

<img width="421" alt="Snipaste_2024-11-12_12-01-23" src="https://github.com/user-attachments/assets/d86d0c64-9209-482e-ba85-119fed1c0327">

**系统信息 / System Informations**
Firefox 131.0.1, Windows 11

谢谢！
Thanks!

moscams

**Comment by SamToki** [comment]
感谢反馈！我会尽快修复

**Comment by SamToki** [comment]
已紧急修复，再次多谢你的反馈！

----------

### Bug 详情

在五天前的[更新](https://github.com/SamToki/KanaMaster/commit/eeadd5c98d536695099c1da99daa9f99c36f7d6e)中，我意图优化语言设定（但目前还没有多语言），添加了个「自动」的语言选项。「假名征服者」的高分榜中有记录日期的功能，这个日期的格式会根据语言环境而改变。例如中文环境下可能会显示 2024/11/12，英文环境下显示 Nov 12, 2024。在自动语言引入之前，程序会直接根据语言选项来决定日期格式。而引入之后，因为世界上不存在名为「自动」的语言，所以这里就会出错。

### 解决办法

现在程序会根据当前 HTML 页面的语言属性来决定日期格式。[点击查看代码改动](https://github.com/SamToki/KanaMaster/commit/33d4506155322370ef3233d55754fbfe81bea712)

### 为何测试时没发现 bug

这个 bug 只会在通关一局游戏后，更新高分榜时触发。小版本更新之前，我只会打开页面粗略地浏览，随便操作一下。没有完整地玩一局游戏。

**Comment by SamToki** [comment]
By the way，你的反馈写得非常认真，我很喜欢 (≧▽≦)
还有，我也用 Firefox，虽然市占率可怜，但用起来就是比 Chrome 舒服

**Comment by moscams** [comment]
> By the way，你的反馈写得非常认真，我很喜欢 (≧▽≦) 还有，我也用 Firefox，虽然市占率可怜，但用起来就是比 Chrome 舒服

谢谢你的快速修复，问题得到了解决~我也很喜欢 Firefox 🦊
